language: ruby

dist: xenial

cache:
  bundler: true

bundler_args: --without debugging

script: bundle exec rake ci

rvm:
  - truffleruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - JRUBY_OPTS="--dev"
